server:
  port: 8085

spring:
  application:
    name: auth-service

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://database-1.cjwa24k2srfd.us-east-2.rds.amazonaws.com:3306/users_db
    username: root
    password: groupproject

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

rabbitmq:
  connection:
    host: b-420b96b0-7ce2-4393-9684-0ede382d6959.mq.us-east-2.amazonaws.com
    port: 5671
    username: groupproject
    password: groupproject
    ssl:
      enabled: true
  queue:
    name: email_service_queue

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true

verification:
  email:
    url: http://localhost:8080/auth/validate?token=

token:
  expiration:
    hours: 3

jwt:
  issuer: auth_service
  ttl:
    millis: 1800000
