server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - Content-Type
              - Authorization
            allowCredentials: true
      routes:
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**

        - id: posts-service
          uri: lb://POSTS-SERVICE
          predicates:
            - Path=/posts/**
          filters:
            - AuthenticationFilter

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: d1M0MTVCMjFaUnRoZE9iZWlVY0VXMlVNWnBTSEhDNFNWQVpiLTlNdkJHdy1qRnRYUncydjFnRnY0M20yUXF4NXd6WFk2MDBHODhaYjZBd05Yc21zVlE=