server:
  port: 8086

spring:
  application:
    name: file-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
      registerWithEureka: true
      fetchRegistry: true